version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mmo_game
      - SECRET_KEY=your_secret_key_here
      - FLASK_APP=app.py
    volumes:
      - ./logs:/app/logs
      - ./templates:/app/templates
      - ./static:/app/static


  mongo:
    image: mongo:latest
    ports:
      - "27020:27020"
    # ports: [SECURITY]
    # - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: