version: '3.8'

services:
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - IN_DOCKER=1
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs

volumes:
  mongo-data:
